#!/bin/bash

# inssfx [suffix] [-h] [-d] [-v] [fname] [--] [fname...]

print_help()
{
    echo "The script should insert the given suffix before the file extention (e.g. "sfx": "a" -> "asfx", "a.txt" -> "asfx.txt", "a.b.c" -> a.bsfx.c)"
    echo -e "\ninssfx [suffix] [-h] [-d] [-v] [fname] [--] [fname...] \n"
    echo "The first non-optional argument is a suffix. All of the next ones are filenames of the file Options:"
    echo -e "\t-h \t print help"
    echo -e "\t-d \t print new fnames without renaming the file"
    echo -e "\t-v \t print the new filenames (which is off by default)"
}

d_flag=0
v_flag=0
if_sfx_exist=0
flist=0
separator=0

# reading the options
# figuring out the sfx existence
# figuring out the filelist existence
for param in "$@"
do
    if [[ $separator -eq 0 ]]
    then
        case $param in
        -h) print_help
            exit 0
            ;;
        -d) d_flag=1
            continue
            ;;
        -v) v_flag=1
            continue
            ;;
        --) separator=1
            continue
            ;;
        -*) echo "invalid option: ${param}. skip" >&2
            continue
            ;;
        esac
    fi

    if [[ $if_sfx_exist -eq 0 ]]
    then
        if_sfx_exist=1
    else
        flist=1
    fi
done

if [[ $if_sfx_exist -eq 0 ]]
then
    echo "No given suffix. Abort" >&2
    exit 1
fi

if [[ $flist -eq 0 ]]
then
    echo "No given files list. Abort" >&2
    exit 2
fi

if_sfx_read=0
separator=0
sfx=""

for param in "$@"
do
    if [[ $separator -eq 0 ]]
    then
        case $param in
        --) separator=1
            continue
            ;;
        -*) continue
            ;;
        esac
    fi

    if [[ $if_sfx_read -eq 0 ]]
    then
        if_sfx_read=1
        sfx=$param
        continue
    fi

    fname=$param

    if [[ !(-e "$fname") ]]
    then
        echo "File $fname doesn't exist. Skip" >&2
        continue
    fi

    if [[ !($fname =~ .*[/].*) ]]
    then
        fname="./${fname}"
    fi

    path=${fname%/*}
    fname=${fname##*/}
    if [[ $fname =~ .*[.].* ]]
    then
        ext=".${fname##*.}"
    else
        ext=""
    fi
    fname_no_ext=${fname%.*}

    if [[ !($d_flag -eq 0) || !($v_flag -eq 0) ]]
    then
        echo "$path/$fname_no_ext$ext -> $path/$fname_no_ext$sfx$ext"
    fi

    if [[ $d_flag -eq 0 ]]
    then
        mv "$path/$fname_no_ext$ext" "$path/$fname_no_ext$sfx$ext"
    fi
done
